import type { MigrationInterface, QueryRunner } from "typeorm";

export class FixUserTableSchema1762880959625 implements MigrationInterface {
    name = 'FixUserTableSchema1762880959625'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "admin_audit_log" DROP CONSTRAINT "FK_admin_audit_log_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" DROP CONSTRAINT "FK_admin_sessions_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" DROP CONSTRAINT "FK_chatroom_members_user_id"`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" DROP CONSTRAINT "FK_chatroom_members_chatroom_id"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_coupon_redemptions_user_id"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_coupon_redemptions_coupon_id"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_job_applications_reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_job_applications_user_id"`);
        await queryRunner.query(`ALTER TABLE "application_reviews" DROP CONSTRAINT "FK_application_reviews_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "application_reviews" DROP CONSTRAINT "FK_application_reviews_application_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_sender_id"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_messages_room_id"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_alerts_created_by"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_alerts_coupon_id"`);
        await queryRunner.query(`ALTER TABLE "application_documents" DROP CONSTRAINT "FK_application_documents_application_id"`);
        await queryRunner.query(`ALTER TABLE "fcm_devices" DROP CONSTRAINT "FK_fcm_devices_user_id"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_product_id"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_favorites_user_id"`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP CONSTRAINT "FK_notification_history_user_id"`);
        await queryRunner.query(`ALTER TABLE "product_features" DROP CONSTRAINT "FK_product_features_feature_id"`);
        await queryRunner.query(`ALTER TABLE "product_features" DROP CONSTRAINT "FK_product_features_product_id"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_features_subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_product_images_product_id"`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" DROP CONSTRAINT "FK_recently_viewed_product_id"`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" DROP CONSTRAINT "FK_recently_viewed_user_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_user_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_reviews_product_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_approved_by"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_moderated_by"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_user_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_products_category_id"`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" DROP CONSTRAINT "FK_ad_moderation_history_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" DROP CONSTRAINT "FK_ad_moderation_history_ad_id"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "FK_subcategories_category_id"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_referrals_referred_user_id"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_referrals_referrer_id"`);
        await queryRunner.query(`ALTER TABLE "referral_redemptions" DROP CONSTRAINT "FK_referral_redemptions_user_id"`);
        await queryRunner.query(`ALTER TABLE "search_history" DROP CONSTRAINT "FK_search_history_user_id"`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP CONSTRAINT "FK_support_cases_assigned_admin_id"`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP CONSTRAINT "FK_support_cases_user_id"`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" DROP CONSTRAINT "FK_support_case_assignments_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" DROP CONSTRAINT "FK_support_case_assignments_case_id"`);
        await queryRunner.query(`ALTER TABLE "support_messages" DROP CONSTRAINT "FK_support_messages_case_id"`);
        await queryRunner.query(`ALTER TABLE "system_settings" DROP CONSTRAINT "FK_system_settings_updated_by"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_wallet_ledger_wallet_id"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_wallet_ledger_user_id"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "FK_towns_region_id"`);
        await queryRunner.query(`ALTER TABLE "user_analytics" DROP CONSTRAINT "FK_user_analytics_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_user_reports_admin_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_user_reports_reported_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_user_reports_reporter_user_id"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_wallets_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_users_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_audit_log_admin_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_audit_log_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_sessions_admin_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_sessions_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_coupons_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_alerts_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_alerts_created_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_products_moderation_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_subcategories_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_categories_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_support_cases_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_support_cases_assigned_admin"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_system_settings_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_reports_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_reports_reported_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_phone"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "UQ_subcategories_name_category"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "sort_order"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "sort_order"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "muted_until"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "slug" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "display_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "archived" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "slug" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "icon_url" text`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "display_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "archived" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_public_id" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_format" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_bytes" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_width" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_height" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "referral_code" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_ba10055f9ef9690e77cf6445cba" UNIQUE ("referral_code")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "referral_points" bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "level" character varying(20) NOT NULL DEFAULT 'SILVER'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_staff" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_superuser" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "preferred_notification_email" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "preferred_notification_phone" character varying(15)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_from_app" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "muted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mute_reason" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "admin_notes" text`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_status_enum"`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93e8864031fab4b49493c926f7"`);
        await queryRunner.query(`ALTER TABLE "features" DROP COLUMN "subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "features" ADD "subcategory_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category_id" uuid`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "subcategory_id" uuid`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "status" character varying(20) NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "moderation_status"`);
        await queryRunner.query(`DROP TYPE "public"."products_moderation_status_enum"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "moderation_status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "PK_subcategories"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "PK_793ef34ad0a3f86f09d4837007c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "PK_categories"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "regions" DROP CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c"`);
        await queryRunner.query(`ALTER TABLE "regions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "regions" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "regions" ADD CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."support_cases_status_enum"`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD "status" character varying(20) NOT NULL DEFAULT 'open'`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP COLUMN "priority"`);
        await queryRunner.query(`DROP TYPE "public"."support_cases_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD "priority" character varying(20) NOT NULL DEFAULT 'normal'`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "towns" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "towns" DROP COLUMN "region_id"`);
        await queryRunner.query(`ALTER TABLE "towns" ADD "region_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."user_reports_status_enum"`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verification_status"`);
        await queryRunner.query(`DROP TYPE "public"."users_verification_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verification_status" character varying(20) NOT NULL DEFAULT 'unverified'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verification_level"`);
        await queryRunner.query(`DROP TYPE "public"."users_verification_level_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verification_level" character varying(20) NOT NULL DEFAULT 'basic'`);
        await queryRunner.query(`CREATE INDEX "IDX_93e8864031fab4b49493c926f7" ON "features" ("subcategory_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_176b502c5ebd6e72cafbd9d6f7" ON "products" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a5f6868c96e0069e699f33e12" ON "products" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1846199852a695713b1f8f5e9a" ON "products" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2286c6d70b3aaf12046aa7016" ON "products" ("moderation_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7b015bc580ae5179ba5a4f42e" ON "subcategories" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3cbd52956c4cc6fe840422bc6" ON "categories" ("archived") `);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`ALTER TABLE "admin_audit_log" ADD CONSTRAINT "FK_7abbe8f7be301725ce49e822788" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" ADD CONSTRAINT "FK_c1711b1831bdf66b77c3605bcdb" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" ADD CONSTRAINT "FK_ff5e08f25be5a3ed0e486754fd8" FOREIGN KEY ("chatroom_id") REFERENCES "chatrooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" ADD CONSTRAINT "FK_1ab2a70203b9457454ab7928445" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_9df1b9bc48e3eea5da3762f8e56" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_986f8dd830915cf2835f89709df" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_fcfc78a3be953dac2443b9b53db" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_c3999006594d0112ae19443cf27" FOREIGN KEY ("reviewed_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_reviews" ADD CONSTRAINT "FK_37429cb43f4837e1c8a0032ba51" FOREIGN KEY ("application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_reviews" ADD CONSTRAINT "FK_22d981457073eae92e8f9fa2e97" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_1dda4fc8dbeeff2ee71f0088ba0" FOREIGN KEY ("room_id") REFERENCES "chatrooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_13cc1efe00291983890dd809cfa" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_779c7c43268165afb5a947e0562" FOREIGN KEY ("created_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_documents" ADD CONSTRAINT "FK_9ad8ab815e842d67e9aaec900cb" FOREIGN KEY ("application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fcm_devices" ADD CONSTRAINT "FK_cee8e59b0b919e0f0fea8a8e894" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_003e599a9fc0e8f154b6313639f" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD CONSTRAINT "FK_727a17e812879626235bc06cbe3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_features" ADD CONSTRAINT "FK_939542cc775c7bb88faf24b23ab" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_features" ADD CONSTRAINT "FK_e8112444d4a4beec5f7d6dc5360" FOREIGN KEY ("feature_id") REFERENCES "features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_93e8864031fab4b49493c926f7b" FOREIGN KEY ("subcategory_id") REFERENCES "subcategories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" ADD CONSTRAINT "FK_13c5b56da6d00c32cb4c0764a0e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" ADD CONSTRAINT "FK_72ecdebddea783ebe1ef655bbd0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_29565df5a020791583febb73c07" FOREIGN KEY ("moderated_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_641c6d1bb7d127da620b1179175" FOREIGN KEY ("approved_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_176b502c5ebd6e72cafbd9d6f70" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_c9de3a8edea9269ca774c919b9a" FOREIGN KEY ("subcategory_id") REFERENCES "subcategories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" ADD CONSTRAINT "FK_6c3a43769f915528c2015c7f554" FOREIGN KEY ("ad_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" ADD CONSTRAINT "FK_1351bfb68717889cfaddcbab342" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "FK_f7b015bc580ae5179ba5a4f42ec" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_6e8e92ccfe617224a7f30adb6b3" FOREIGN KEY ("referred_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_redemptions" ADD CONSTRAINT "FK_1f68a0ad9eab8af5e5c5ecbcea5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_history" ADD CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD CONSTRAINT "FK_5a99a9d58af4a0e3093e2d14252" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD CONSTRAINT "FK_a39beb2b481b4920b76cf0eed86" FOREIGN KEY ("assigned_admin_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" ADD CONSTRAINT "FK_eb01a5e4cc56c669816c6d9fc05" FOREIGN KEY ("case_id") REFERENCES "support_cases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" ADD CONSTRAINT "FK_7d3ff3317ac3b668637efbff05f" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_messages" ADD CONSTRAINT "FK_8c825aa202717f0516b512168d0" FOREIGN KEY ("case_id") REFERENCES "support_cases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_settings" ADD CONSTRAINT "FK_301c531938f84c39fa5019e7465" FOREIGN KEY ("updated_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_53d9fecd40f5fe635d119b49c4d" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "FK_bc6fdd078791390d8be81a62857" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_analytics" ADD CONSTRAINT "FK_1b21a2704e98eb4ad610a671f2a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_a3c4ba2f4a0cdd6ebcfdebd97ab" FOREIGN KEY ("reporter_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_006c1307e23fea0915e8cf1882a" FOREIGN KEY ("reported_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_f6b9af9e74c67dd269b22d9d84a" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_92558c08091598f7a4439586cda" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_92558c08091598f7a4439586cda"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_f6b9af9e74c67dd269b22d9d84a"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_006c1307e23fea0915e8cf1882a"`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP CONSTRAINT "FK_a3c4ba2f4a0cdd6ebcfdebd97ab"`);
        await queryRunner.query(`ALTER TABLE "user_analytics" DROP CONSTRAINT "FK_1b21a2704e98eb4ad610a671f2a"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "FK_bc6fdd078791390d8be81a62857"`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" DROP CONSTRAINT "FK_53d9fecd40f5fe635d119b49c4d"`);
        await queryRunner.query(`ALTER TABLE "system_settings" DROP CONSTRAINT "FK_301c531938f84c39fa5019e7465"`);
        await queryRunner.query(`ALTER TABLE "support_messages" DROP CONSTRAINT "FK_8c825aa202717f0516b512168d0"`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" DROP CONSTRAINT "FK_7d3ff3317ac3b668637efbff05f"`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" DROP CONSTRAINT "FK_eb01a5e4cc56c669816c6d9fc05"`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP CONSTRAINT "FK_a39beb2b481b4920b76cf0eed86"`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP CONSTRAINT "FK_5a99a9d58af4a0e3093e2d14252"`);
        await queryRunner.query(`ALTER TABLE "search_history" DROP CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2"`);
        await queryRunner.query(`ALTER TABLE "referral_redemptions" DROP CONSTRAINT "FK_1f68a0ad9eab8af5e5c5ecbcea5"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_6e8e92ccfe617224a7f30adb6b3"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_18af9fcaffac6d6d3b28130e149"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "FK_f7b015bc580ae5179ba5a4f42ec"`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" DROP CONSTRAINT "FK_1351bfb68717889cfaddcbab342"`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" DROP CONSTRAINT "FK_6c3a43769f915528c2015c7f554"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_c9de3a8edea9269ca774c919b9a"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_176b502c5ebd6e72cafbd9d6f70"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_641c6d1bb7d127da620b1179175"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_29565df5a020791583febb73c07"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_9482e9567d8dcc2bc615981ef44"`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" DROP CONSTRAINT "FK_72ecdebddea783ebe1ef655bbd0"`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" DROP CONSTRAINT "FK_13c5b56da6d00c32cb4c0764a0e"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_4f166bb8c2bfcef2498d97b4068"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_93e8864031fab4b49493c926f7b"`);
        await queryRunner.query(`ALTER TABLE "product_features" DROP CONSTRAINT "FK_e8112444d4a4beec5f7d6dc5360"`);
        await queryRunner.query(`ALTER TABLE "product_features" DROP CONSTRAINT "FK_939542cc775c7bb88faf24b23ab"`);
        await queryRunner.query(`ALTER TABLE "notification_history" DROP CONSTRAINT "FK_727a17e812879626235bc06cbe3"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_003e599a9fc0e8f154b6313639f"`);
        await queryRunner.query(`ALTER TABLE "favorites" DROP CONSTRAINT "FK_35a6b05ee3b624d0de01ee50593"`);
        await queryRunner.query(`ALTER TABLE "fcm_devices" DROP CONSTRAINT "FK_cee8e59b0b919e0f0fea8a8e894"`);
        await queryRunner.query(`ALTER TABLE "application_documents" DROP CONSTRAINT "FK_9ad8ab815e842d67e9aaec900cb"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_779c7c43268165afb5a947e0562"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_13cc1efe00291983890dd809cfa"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_1dda4fc8dbeeff2ee71f0088ba0"`);
        await queryRunner.query(`ALTER TABLE "application_reviews" DROP CONSTRAINT "FK_22d981457073eae92e8f9fa2e97"`);
        await queryRunner.query(`ALTER TABLE "application_reviews" DROP CONSTRAINT "FK_37429cb43f4837e1c8a0032ba51"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_c3999006594d0112ae19443cf27"`);
        await queryRunner.query(`ALTER TABLE "job_applications" DROP CONSTRAINT "FK_fcfc78a3be953dac2443b9b53db"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_986f8dd830915cf2835f89709df"`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" DROP CONSTRAINT "FK_9df1b9bc48e3eea5da3762f8e56"`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" DROP CONSTRAINT "FK_1ab2a70203b9457454ab7928445"`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" DROP CONSTRAINT "FK_ff5e08f25be5a3ed0e486754fd8"`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" DROP CONSTRAINT "FK_c1711b1831bdf66b77c3605bcdb"`);
        await queryRunner.query(`ALTER TABLE "admin_audit_log" DROP CONSTRAINT "FK_7abbe8f7be301725ce49e822788"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3cbd52956c4cc6fe840422bc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7b015bc580ae5179ba5a4f42e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2286c6d70b3aaf12046aa7016"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1846199852a695713b1f8f5e9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a5f6868c96e0069e699f33e12"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_176b502c5ebd6e72cafbd9d6f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93e8864031fab4b49493c926f7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verification_level"`);
        await queryRunner.query(`CREATE TYPE "public"."users_verification_level_enum" AS ENUM('basic', 'advanced', 'premium')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verification_level" "public"."users_verification_level_enum" NOT NULL DEFAULT 'basic'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "verification_status"`);
        await queryRunner.query(`CREATE TYPE "public"."users_verification_status_enum" AS ENUM('unverified', 'pending', 'verified')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "verification_status" "public"."users_verification_status_enum" NOT NULL DEFAULT 'unverified'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "user_reports" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."user_reports_status_enum" AS ENUM('pending', 'resolved', 'dismissed')`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD "status" "public"."user_reports_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "towns" DROP COLUMN "region_id"`);
        await queryRunner.query(`ALTER TABLE "towns" ADD "region_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "towns" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP COLUMN "priority"`);
        await queryRunner.query(`CREATE TYPE "public"."support_cases_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD "priority" "public"."support_cases_priority_enum" NOT NULL DEFAULT 'normal'`);
        await queryRunner.query(`ALTER TABLE "support_cases" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."support_cases_status_enum" AS ENUM('open', 'in-progress', 'resolved', 'closed')`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD "status" "public"."support_cases_status_enum" NOT NULL DEFAULT 'open'`);
        await queryRunner.query(`ALTER TABLE "regions" DROP CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c"`);
        await queryRunner.query(`ALTER TABLE "regions" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "regions" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "regions" ADD CONSTRAINT "PK_4fcd12ed6a046276e2deb08801c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "PK_categories" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "category_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP CONSTRAINT "PK_793ef34ad0a3f86f09d4837007c"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "PK_subcategories" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "moderation_status"`);
        await queryRunner.query(`CREATE TYPE "public"."products_moderation_status_enum" AS ENUM('pending', 'active', 'suspended', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "moderation_status" "public"."products_moderation_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'active', 'paused', 'archived', 'sold')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "subcategory_id" integer`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "category_id" integer`);
        await queryRunner.query(`ALTER TABLE "features" DROP COLUMN "subcategory_id"`);
        await queryRunner.query(`ALTER TABLE "features" ADD "subcategory_id" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_93e8864031fab4b49493c926f7" ON "features" ("subcategory_id") `);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_status_enum" AS ENUM('draft', 'active', 'scheduled', 'sent', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "status" "public"."alerts_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "admin_notes"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mute_reason"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "muted_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_from_app"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "preferred_notification_phone"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "preferred_notification_email"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_verified"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_superuser"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_staff"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "referral_points"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_ba10055f9ef9690e77cf6445cba"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "referral_code"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_height"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_width"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_bytes"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_format"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_public_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "archived"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "display_order"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "icon_url"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "archived"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "display_order"`);
        await queryRunner.query(`ALTER TABLE "subcategories" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "location" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "display_name" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "muted_until" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "icon" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "sort_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "image_url" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "icon" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "sort_order" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "UQ_subcategories_name_category" UNIQUE ("name", "category_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_reports_reported_user" ON "user_reports" ("reported_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_reports_status" ON "user_reports" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_system_settings_key" ON "system_settings" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_support_cases_assigned_admin" ON "support_cases" ("assigned_admin_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_support_cases_status" ON "support_cases" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_categories_name" ON "categories" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_subcategories_category_id" ON "subcategories" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_moderation_status" ON "products" ("moderation_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_status" ON "products" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_user_id" ON "products" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_products_category_id" ON "products" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_alerts_created_by" ON "alerts" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_alerts_status" ON "alerts" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_coupons_code" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_sessions_expires_at" ON "admin_sessions" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_sessions_admin_user" ON "admin_sessions" ("admin_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_audit_log_created_at" ON "admin_audit_log" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_audit_log_admin_user" ON "admin_audit_log" ("admin_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_users_active" ON "admin_users" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_users_role" ON "admin_users" ("role") `);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_wallets_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_user_reports_reporter_user_id" FOREIGN KEY ("reporter_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_user_reports_reported_user_id" FOREIGN KEY ("reported_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_reports" ADD CONSTRAINT "FK_user_reports_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_analytics" ADD CONSTRAINT "FK_user_analytics_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "FK_towns_region_id" FOREIGN KEY ("region_id") REFERENCES "regions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_wallet_ledger_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_ledger" ADD CONSTRAINT "FK_wallet_ledger_wallet_id" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_settings" ADD CONSTRAINT "FK_system_settings_updated_by" FOREIGN KEY ("updated_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_messages" ADD CONSTRAINT "FK_support_messages_case_id" FOREIGN KEY ("case_id") REFERENCES "support_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" ADD CONSTRAINT "FK_support_case_assignments_case_id" FOREIGN KEY ("case_id") REFERENCES "support_cases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_case_assignments" ADD CONSTRAINT "FK_support_case_assignments_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD CONSTRAINT "FK_support_cases_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_cases" ADD CONSTRAINT "FK_support_cases_assigned_admin_id" FOREIGN KEY ("assigned_admin_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_history" ADD CONSTRAINT "FK_search_history_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_redemptions" ADD CONSTRAINT "FK_referral_redemptions_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_referrals_referrer_id" FOREIGN KEY ("referrer_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_referrals_referred_user_id" FOREIGN KEY ("referred_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subcategories" ADD CONSTRAINT "FK_subcategories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" ADD CONSTRAINT "FK_ad_moderation_history_ad_id" FOREIGN KEY ("ad_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ad_moderation_history" ADD CONSTRAINT "FK_ad_moderation_history_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_category_id" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_subcategory_id" FOREIGN KEY ("subcategory_id") REFERENCES "subcategories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_moderated_by" FOREIGN KEY ("moderated_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_products_approved_by" FOREIGN KEY ("approved_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_reviews_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" ADD CONSTRAINT "FK_recently_viewed_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recently_viewed" ADD CONSTRAINT "FK_recently_viewed_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_product_images_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_features_subcategory_id" FOREIGN KEY ("subcategory_id") REFERENCES "subcategories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_features" ADD CONSTRAINT "FK_product_features_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_features" ADD CONSTRAINT "FK_product_features_feature_id" FOREIGN KEY ("feature_id") REFERENCES "features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_history" ADD CONSTRAINT "FK_notification_history_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "favorites" ADD CONSTRAINT "FK_favorites_product_id" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fcm_devices" ADD CONSTRAINT "FK_fcm_devices_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_documents" ADD CONSTRAINT "FK_application_documents_application_id" FOREIGN KEY ("application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_alerts_coupon_id" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_alerts_created_by" FOREIGN KEY ("created_by") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_room_id" FOREIGN KEY ("room_id") REFERENCES "chatrooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_messages_sender_id" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_reviews" ADD CONSTRAINT "FK_application_reviews_application_id" FOREIGN KEY ("application_id") REFERENCES "job_applications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_reviews" ADD CONSTRAINT "FK_application_reviews_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_job_applications_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_applications" ADD CONSTRAINT "FK_job_applications_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_coupon_redemptions_coupon_id" FOREIGN KEY ("coupon_id") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_redemptions" ADD CONSTRAINT "FK_coupon_redemptions_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" ADD CONSTRAINT "FK_chatroom_members_chatroom_id" FOREIGN KEY ("chatroom_id") REFERENCES "chatrooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chatroom_members" ADD CONSTRAINT "FK_chatroom_members_user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_sessions" ADD CONSTRAINT "FK_admin_sessions_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_audit_log" ADD CONSTRAINT "FK_admin_audit_log_admin_user_id" FOREIGN KEY ("admin_user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
